name: agforge

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]

jobs:
  title_check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'synchronize' }}
    steps:
      - uses: actions/github-script@v9
        with:
          script: |
            const regex = RegExp("^\\[(ci|docs|forge|tests)\\] .+ #[\\d]+$")
            const title = context.payload.pull_request.title

            if (!regex.test(title)) {
                core.setFailed(`PR title "${title}" failed to pass regex - ${regex}. Correct example: [ci] description #1`);
            }

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'edited' }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov --all-features --show-missing-lines

  version:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: version
        run: |
          PREVIOUS_VERSION=$(git tag --sort=-v:refname | head -n 1)
          CURRENT_VERSION=$(cat agforge/Cargo.toml | grep version | awk '{print $3}' | tr -d '"')
          if [ "$PREVIOUS_VERSION" != "$CURRENT_VERSION" ]; then
            echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          fi

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [version]
    if: ${{ needs.version.outputs.new_version != '' }}
    steps:
      - uses: actions/checkout@v6
      - run: |
          VERSION=${{ needs.version.outputs.new_version }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.new_version }}
          generate_release_notes: true

  publish:
    runs-on: ubuntu-latest
    needs: [version]
    if: ${{ needs.version.outputs.new_version != '' }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cargo publish -p agforge --token ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
